[package]
name = "RustyTrades"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
tokio-tungstenite = { version = "0.20", features = ["native-tls"] }
futures-util = "0.3"
serde_json = "1.0.128"
url = "2.4"
anyhow = "1.0"
chrono = "0.4.38"
reqwest = { version = "0.12.9", features = ["json"] }
iced = { version = "0.13.1", features = ["canvas", "tokio"] }
serde = { version = "1.0.210", features = ["derive"] }
rand = "0.8.5"
iced_futures = "0.13.2"
async-stream = "0.3"