refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    filters:
      - kind: threshold
        level: info
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)(utc)} - {l}:{m}{n}"

  file:
    kind: file
    path: "logs/trading.log"
    filters:
      - kind: threshold
        level: info
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)(utc)} - {l}:{m}{n}"

root:
  level: info
  appenders:
    - stdout
    - file